Repository CS2103-AY1819S1-W14-4/main, pull requests merged in 2018-09, with the labels that each got.

#5 Updated ReadMe and added Darren's profile
  README.adoc
  docs/AboutUs.adoc
  docs/images/darren96.jpeg
  docs/team/darren96.adoc
Labels: priority.high, type.task

#6 Updated About Us and User Guide
  docs/AboutUs.adoc
  docs/UserGuide.adoc
  docs/images/zulq9.jpg
  docs/team/zulq9.adoc
Labels: priority.high, type.task

#7 Updated About Us
  docs/AboutUs.adoc
  docs/images/yao-tx.jpg
  docs/team/yao-tx.adoc
Labels: type.task

#9 Updated the developer guide
  README.adoc
  docs/DeveloperGuide.adoc
Labels: priority.high

#17 Change team images to .png file type
  docs/images/darren96.png
  docs/images/esmondtan.png
  docs/images/fzdy1914.png
  docs/images/yao-tx.png
  docs/images/zulq9.png
Labels: type.story
