Repository CS2103-AY1819S1-W14-4/main, pull requests merged in 2018-11, with the labels that each got.

#150 Updated DG and PPP
  docs/DeveloperGuide.adoc
  docs/images/ComingSoon.png
  docs/team/zulq9.adoc
Labels: component.docs, status.done

#153 Fixed image
  docs/UserGuide.adoc
  docs/images/Ui.png
Labels: component.docs, severity.high, status.done

#149 Fix small bug of Csv Adapted Po
  docs/team/fzdy1914.adoc
  src/main/java/seedu/inventory/MainApp.java
  src/main/java/seedu/inventory/storage/CsvAdaptedPurchaseOrder.java
Labels: status.done

#155 Readme.adoc: Fix broken image
  README.adoc
Labels: component.docs, status.done

#171 Fixed up the issues raised in PE dry run
  docs/UserGuide.adoc
  src/main/java/seedu/inventory/logic/commands/item/AddItemCommand.java
  src/main/java/seedu/inventory/model/item/FilterPrice.java
  src/main/java/seedu/inventory/model/item/FilterQuantity.java
  src/main/java/seedu/inventory/model/item/Quantity.java
Labels: severity.high, status.done, type.bug

#172 Resolves bugs found PE Dry Run.
  docs/UserGuide.adoc
  src/main/java/seedu/inventory/logic/CommandHistory.java
  src/main/java/seedu/inventory/logic/LogicManager.java
  src/main/java/seedu/inventory/logic/commands/authentication/LoginCommand.java
  src/main/java/seedu/inventory/logic/commands/authentication/LogoutCommand.java
  src/main/java/seedu/inventory/logic/commands/staff/DeleteStaffCommand.java
  src/test/java/seedu/inventory/logic/CommandHistoryTest.java
  src/test/java/seedu/inventory/logic/LogicManagerTest.java
Labels: priority.medium, status.done, type.bug

#189 Updated Ug to fix pe dry run issues
  docs/UserGuide.adoc
Labels: status.done

#190 Categories Csv Related Class into its own package
  src/main/java/seedu/inventory/MainApp.java
  src/main/java/seedu/inventory/commons/events/model/StaffListImportEvent.java
  src/main/java/seedu/inventory/commons/util/CsvUtil.java
  src/main/java/seedu/inventory/logic/commands/csv/ExportCsvCommand.java
  src/main/java/seedu/inventory/logic/commands/csv/ImportCsvCommand.java
  src/main/java/seedu/inventory/logic/parser/InventoryParser.java
  src/main/java/seedu/inventory/logic/parser/csv/ExportCsvCommandParser.java
  src/main/java/seedu/inventory/logic/parser/csv/ImportCsvCommandParser.java
  src/main/java/seedu/inventory/storage/csv/CsvAdaptedItem.java
  src/main/java/seedu/inventory/storage/csv/CsvAdaptedPurchaseOrder.java
  src/main/java/seedu/inventory/storage/csv/CsvAdaptedSale.java
  src/main/java/seedu/inventory/storage/csv/CsvAdaptedStaff.java
  src/main/java/seedu/inventory/storage/csv/CsvAdaptedTag.java
  src/main/java/seedu/inventory/storage/csv/CsvReportingStorage.java
  src/main/java/seedu/inventory/storage/csv/CsvSerializableData.java
  src/main/java/seedu/inventory/storage/csv/CsvSerializableItemList.java
  src/main/java/seedu/inventory/storage/csv/CsvSerializablePurchaseOrderList.java
  src/main/java/seedu/inventory/storage/csv/CsvSerializableSaleList.java
  src/main/java/seedu/inventory/storage/csv/CsvSerializableStaffList.java
  src/test/java/seedu/inventory/commons/util/CsvUtilTest.java
  src/test/java/seedu/inventory/logic/commands/ExportCsvCommandTest.java
  src/test/java/seedu/inventory/logic/commands/ImportCsvCommandTest.java
  src/test/java/seedu/inventory/logic/parser/ExportCsvCommandParserTest.java
  src/test/java/seedu/inventory/logic/parser/ImportCsvCommandParserTest.java
  src/test/java/seedu/inventory/logic/parser/InventoryParserTest.java
  src/test/java/seedu/inventory/storage/CsvAdaptedItemTest.java
  src/test/java/seedu/inventory/storage/CsvAdaptedPurchaseOrderTest.java
  src/test/java/seedu/inventory/storage/CsvAdaptedSaleTest.java
  src/test/java/seedu/inventory/storage/CsvAdaptedStaffTest.java
  src/test/java/seedu/inventory/storage/CsvAdaptedTagTest.java
  src/test/java/seedu/inventory/storage/CsvReportingStorageTest.java
  src/test/java/seedu/inventory/storage/CsvSerializableItemListTest.java
  src/test/java/seedu/inventory/storage/CsvSerializablePurchaseOrderListTest.java
  src/test/java/seedu/inventory/storage/CsvSerializableSaleListTest.java
  src/test/java/seedu/inventory/storage/CsvSerializableStaffListTest.java
  src/test/java/seedu/inventory/storage/StorageManagerTest.java
Labels: priority.medium, status.done

#193 Refresh result pannel before the alert pop up
  src/main/java/seedu/inventory/logic/commands/csv/ExportCsvCommand.java
  src/main/java/seedu/inventory/logic/commands/csv/ImportCsvCommand.java
  src/main/java/seedu/inventory/storage/StorageManager.java
Labels: priority.medium, status.done

#195 Bug fixes for trivial bugs
  src/main/java/seedu/inventory/MainApp.java
  src/main/java/seedu/inventory/logic/commands/sale/AddSaleCommand.java
  src/main/java/seedu/inventory/logic/commands/sale/DeleteSaleCommand.java
  src/main/java/seedu/inventory/logic/parser/ParserUtil.java
  src/main/java/seedu/inventory/model/Inventory.java
  src/main/java/seedu/inventory/model/ModelManager.java
  src/main/java/seedu/inventory/model/ReadOnlyInventory.java
  src/main/java/seedu/inventory/model/item/Quantity.java
  src/test/java/seedu/inventory/logic/commands/sale/AddSaleCommandTest.java
  src/test/java/seedu/inventory/logic/commands/sale/DeleteSaleCommandTest.java
  src/test/java/seedu/inventory/model/InventoryTest.java
  src/test/java/seedu/inventory/model/item/QuantityTest.java
Labels: status.done

#196 Bug fix and masking password in log
  src/main/java/seedu/inventory/logic/Logic.java
  src/main/java/seedu/inventory/logic/LogicManager.java
  src/main/java/seedu/inventory/logic/commands/authentication/LoginCommand.java
  src/main/java/seedu/inventory/logic/parser/ParserUtil.java
  src/main/java/seedu/inventory/model/staff/Password.java
  src/main/java/seedu/inventory/storage/XmlAdaptedStaff.java
  src/main/java/seedu/inventory/storage/csv/CsvAdaptedStaff.java
  src/test/data/CsvSerializableStaffListTest/duplicateStaffList.csv
  src/test/data/XmlSerializableStaffListTest/duplicateStaffStaffList.xml
  src/test/java/seedu/inventory/logic/LogicManagerTest.java
  src/test/java/seedu/inventory/model/staff/PasswordTest.java
  src/test/java/seedu/inventory/testutil/staff/StaffBuilder.java
  src/test/java/seedu/inventory/ui/StaffListPanelTest.java
Labels: status.done

#194 System test add for csv command
  src/test/data/ImportCsvCommandSystemTest/duplicateItemList.csv
  src/test/data/ImportCsvCommandSystemTest/invalidItemList.csv
  src/test/data/ImportCsvCommandSystemTest/typicalItemList.csv
  src/test/java/systemtests/ErrorDialogGuiTest.java
  src/test/java/systemtests/ExportCsvCommandSystemTest.java
  src/test/java/systemtests/ImportCsvCommandSystemTest.java
  src/test/java/systemtests/InformationDialogGuiTest.java
  src/test/java/systemtests/InventorySystemTest.java
Labels: priority.high, status.done

#198 Add Table View
  .gitignore
  src/main/java/seedu/inventory/commons/events/ui/ShowBrowserPanelEvent.java
  src/main/java/seedu/inventory/commons/events/ui/ShowDefaultPageEvent.java
  src/main/java/seedu/inventory/commons/events/ui/ShowItemTableViewEvent.java
  src/main/java/seedu/inventory/commons/events/ui/ShowPurchaseOrderTableViewEvent.java
  src/main/java/seedu/inventory/commons/events/ui/ShowSaleTableViewEvent.java
  src/main/java/seedu/inventory/commons/events/ui/ShowStaffTableViewEvent.java
  src/main/java/seedu/inventory/model/Model.java
  src/main/java/seedu/inventory/model/ModelManager.java
  src/main/java/seedu/inventory/ui/BrowserPanel.java
  src/main/java/seedu/inventory/ui/ItemTableView.java
  src/main/java/seedu/inventory/ui/MainWindow.java
  src/main/java/seedu/inventory/ui/PurchaseOrderTableView.java
  src/main/java/seedu/inventory/ui/SaleTableView.java
  src/main/java/seedu/inventory/ui/StaffTableView.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ItemTableView.fxml
  src/main/resources/view/PurchaseOrderTableView.fxml
  src/main/resources/view/SaleTableView.fxml
  src/main/resources/view/StaffTableView.fxml
  src/test/java/seedu/inventory/model/ModelManagerTest.java
  src/test/java/seedu/inventory/testutil/ModelStub.java
Labels: status.done

#151 darren96.adoc: add more docs
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/darren96.adoc
Labels: status.done

#199 Update table view test
  src/main/resources/view/ItemTableView.fxml
  src/main/resources/view/PurchaseOrderTableView.fxml
  src/main/resources/view/SaleTableView.fxml
  src/main/resources/view/StaffTableView.fxml
  src/test/java/guitests/guihandles/ItemTableViewHandle.java
  src/test/java/guitests/guihandles/PurchaseOrderTableViewHandle.java
  src/test/java/guitests/guihandles/SaleTableViewHandle.java
  src/test/java/guitests/guihandles/StaffTableViewHandle.java
  src/test/java/seedu/inventory/ui/ItemTableViewTest.java
  src/test/java/seedu/inventory/ui/PurchaseOrderTableViewTest.java
  src/test/java/seedu/inventory/ui/SaleTableViewTest.java
  src/test/java/seedu/inventory/ui/StaffTableViewTest.java
Labels: status.done

#202 Fix bug of export csv sales
  src/main/java/seedu/inventory/model/ModelManager.java
Labels: status.done

#203 Support Undo Redo for Csv Import
  src/main/java/seedu/inventory/logic/commands/csv/ImportCsvCommand.java
  src/main/java/seedu/inventory/model/ModelManager.java
Labels: status.done

#204 UG, DG, PPP updates
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/AddSaleCommandSequenceDiagram.pptx
  docs/images/AddSaleCommandSequenceDiagram.png
  docs/team/esmondtan.adoc
  src/main/java/seedu/inventory/model/ModelManager.java
Labels: status.done

#205 added numbering
  docs/team/esmondtan.adoc
Labels: status.done

#207 Fixed up PPP and DG tag issue
  docs/DeveloperGuide.adoc
  docs/team/yao-tx.adoc
Labels: component.docs, status.done, type.bug

#208 Update storage and Ui class diagram
  docs/diagrams/StorageComponentClassDiagram.pptx
  docs/diagrams/UiComponentClassDiagram.pptx
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: component.docs, status.done

#209 Updates on ModelClassDiagram
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/images/ModelClassDiagram.png
Labels: component.docs, status.done

#210 Updated PPP, UGDG and added more images
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/PoAdd.png
  docs/images/PoCard.PNG
  docs/images/PoCommand.png
  docs/images/PoList.png
  docs/images/PoModel1.png
  docs/images/PoModel2.png
  docs/images/PoStorage.png
  docs/images/PoUi.png
  docs/images/doc-add-po.PNG
  docs/images/doc-delete-po.png
  docs/team/zulq9.adoc
Labels: component.docs, status.done

#191 Update UG, DG, PPP. Also Imporved Undo/Redo
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ExportCsvItemCommandSequenceDiagram.pptx
  docs/diagrams/HighLevelSequenceDiagramsForExportCsvItem.pptx
  docs/diagrams/UndoRedoActivityDiagram.pptx
  docs/diagrams/UndoRedoExecuteUndoStateListDiagram.pptx
  docs/diagrams/UndoRedoNewCommand1StateListDiagram.pptx
  docs/diagrams/UndoRedoNewCommand2StateListDiagram.pptx
  docs/diagrams/UndoRedoNewCommand3StateListDiagram.pptx
  docs/diagrams/UndoRedoNewCommand4StateListDiagram.pptx
  docs/diagrams/UndoRedoSequenceDiagram.pptx
  docs/diagrams/UndoRedoStartingStateListDiagram.pptx
  docs/images/ExportCsvItemCommandSequenceDiagram.png
  docs/images/SDforExportCsvItem.png
  docs/images/SDforExportCsvItemEventHandling.png
  docs/images/UndoRedoActivityDiagram.png
  docs/images/UndoRedoExecuteUndoStateListDiagram.png
  docs/images/UndoRedoNewCommand1StateListDiagram.png
  docs/images/UndoRedoNewCommand2StateListDiagram.png
  docs/images/UndoRedoNewCommand3StateListDiagram.png
  docs/images/UndoRedoNewCommand4StateListDiagram.png
  docs/images/UndoRedoSequenceDiagram.png
  docs/images/UndoRedoStartingStateListDiagram.png
  docs/images/doc-export-csv-item.png
  docs/images/doc-export-csv-items.png
  docs/images/doc-import-csv-sales.png
  docs/team/fzdy1914.adoc
Labels: component.docs, status.done

#212 updated UD/DG/PPP
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/esmondtan.adoc
Labels: status.done

#213 Added po test in appendix i
  docs/DeveloperGuide.adoc
Labels: status.done

#211 Updates UGDG for UserManagement and Authentication
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/AuthenticationModelComponentClassDiagram.pptx
  docs/diagrams/EditStaffCommandSequenceDiagram.pptx
  docs/diagrams/LoginCommandSequenceDiagram.pptx
  docs/diagrams/StaffModelComponentClassDiagram.pptx
  docs/diagrams/StaffStorageComponentClassDiagram.pptx
  docs/images/AuthenticationModelComponentClassDiagram.png
  docs/images/EditStaffSDForLogic.png
  docs/images/LoginSDForLogic.png
  docs/images/StaffModelComponentClassDiagram.png
  docs/images/StaffStorageComponentClassDiagram.png
  docs/team/darren96.adoc
Labels: component.docs, status.done

#214 Add Test Case in Appendix
  docs/DeveloperGuide.adoc
Labels: status.done

#216 Refactored image extension name
  docs/images/PoCard.png
  docs/images/doc-add-po.png
Labels: status.done

#218 Finalised my UG, DG and PPP
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/yao-tx.adoc
Labels: component.docs, status.done

#219 Fix edit command bug
  docs/team/zulq9.adoc
  src/main/java/seedu/inventory/logic/commands/purchaseorder/ApprovePurchaseOrderCommand.java
  src/main/java/seedu/inventory/logic/commands/purchaseorder/DeletePurchaseOrderCommand.java
  src/main/java/seedu/inventory/logic/commands/purchaseorder/EditPurchaseOrderCommand.java
  src/main/java/seedu/inventory/logic/commands/purchaseorder/RejectPurchaseOrderCommand.java
  src/main/java/seedu/inventory/model/Inventory.java
  src/main/java/seedu/inventory/model/Model.java
  src/main/java/seedu/inventory/model/ModelManager.java
  src/main/java/seedu/inventory/model/PurchaseOrderList.java
  src/main/java/seedu/inventory/model/purchaseorder/NonUniquePurchaseOrderList.java
  src/test/java/seedu/inventory/logic/commands/CommandTestUtil.java
  src/test/java/seedu/inventory/logic/commands/purchaseorder/ApprovePurchaseOrderCommandTest.java
  src/test/java/seedu/inventory/logic/commands/purchaseorder/DeletePurchaseOrderCommandTest.java
  src/test/java/seedu/inventory/logic/commands/purchaseorder/EditPurchaseOrderCommandTest.java
  src/test/java/seedu/inventory/logic/commands/purchaseorder/RejectPurchaseOrderCommandTest.java
  src/test/java/seedu/inventory/model/InventoryTest.java
  src/test/java/seedu/inventory/model/ModelManagerTest.java
  src/test/java/seedu/inventory/model/PurchaseOrderListTest.java
  src/test/java/seedu/inventory/model/purchaseorder/NonUniquePurchaseOrderListTest.java
  src/test/java/seedu/inventory/testutil/ModelStub.java
Labels: status.done

#217 Finalising UGDG on Authentication and User Management
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/stylesheets/asciidoctor.css
  docs/team/darren96.adoc
Labels: component.docs, status.done

#221 Updated UG/DG and PPP
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/UniqueItemList.pptx
  docs/images/UniqueItemList.png
  docs/team/yao-tx.adoc
Labels: component.docs, status.done

#222 More changes to DG/PPP sorry :(
  docs/UserGuide.adoc
  docs/team/yao-tx.adoc
Labels: component.docs, status.done

#223 More changes to PPP and minor fix sorry :(
  docs/team/zulq9.adoc
  src/main/java/seedu/inventory/model/purchaseorder/RequiredDate.java
Labels: status.done

#224 Bug fix for duplicated username
  src/main/java/seedu/inventory/logic/commands/authentication/ChangePasswordCommand.java
  src/main/java/seedu/inventory/logic/commands/authentication/LoginCommand.java
  src/main/java/seedu/inventory/logic/commands/staff/AddStaffCommand.java
  src/main/java/seedu/inventory/logic/commands/staff/EditStaffCommand.java
  src/main/java/seedu/inventory/logic/commands/staff/ListStaffCommand.java
  src/main/java/seedu/inventory/model/Inventory.java
  src/main/java/seedu/inventory/model/Model.java
  src/main/java/seedu/inventory/model/ModelManager.java
  src/main/java/seedu/inventory/model/staff/Staff.java
  src/main/java/seedu/inventory/model/staff/UniqueStaffList.java
  src/test/java/seedu/inventory/logic/commands/CommandTestUtil.java
  src/test/java/seedu/inventory/logic/commands/staff/AddStaffCommandTest.java
  src/test/java/seedu/inventory/logic/commands/staff/EditStaffCommandTest.java
  src/test/java/seedu/inventory/testutil/ModelStub.java
Labels: priority.high, status.done

#226 Small Change to PPP
  docs/team/fzdy1914.adoc
Labels: status.done

#227 Added a few sample purchase order data in sampleInventory
  docs/UserGuide.adoc
  src/main/java/seedu/inventory/model/util/SampleDataUtil.java
Labels: status.done

#228 Finalized ug and ppp sorry :(
  docs/UserGuide.adoc
  docs/team/zulq9.adoc
Labels: status.done

#229 Added clear event for search/list items related commands
  src/main/java/seedu/inventory/commons/events/ui/ClearBrowserPanelEvent.java
  src/main/java/seedu/inventory/model/ModelManager.java
  src/main/java/seedu/inventory/ui/BrowserPanel.java
Labels: status.done, type.bug

#225 darren96 PPP updates
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/darren96.adoc
Labels: status.done

#232 Update fzdy1914.adoc
  docs/team/fzdy1914.adoc
Labels: status.done

#230 Finalize group UGDG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: status.waiting

#233 Hotfix :(
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/inventory/logic/commands/staff/EditStaffCommand.java
Labels: status.done

#234 Fix burden ppp link
  docs/team/zulq9.adoc
Labels: status.done
