Repository CS2103-AY1819S1-W14-4/main, pull requests merged in 2018-10, with the labels that each got.

#25 [Documentation] Updated UG and DG on purchase order as well as profile portfolio
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/zulq9.adoc
Labels: priority.high, status.done, status.waiting, type.story

#31 [Documentation] UGDG and Personal Portfolio updates
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/darren96.adoc
Labels: priority.high, status.done, type.story

#35 AboutUs.adoc: Change the files' extension to png
  docs/AboutUs.adoc
Labels: status.done

#28 [UI] Enhanced UI to replicate the sketched UI
  copyright.txt
  src/main/java/seedu/inventory/model/UserPrefs.java
  src/main/java/seedu/inventory/ui/UiManager.java
  src/main/resources/images/UI.png
  src/main/resources/images/address_book_32.png
  src/main/resources/images/inventory_manager_32.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/default.html
  src/test/java/seedu/inventory/commons/util/AppUtilTest.java
Labels: status.waiting

#13 Staff Model Created for User Management features
  README.adoc
  src/main/java/seedu/inventory/model/staff/Name.java
  src/main/java/seedu/inventory/model/staff/Password.java
  src/main/java/seedu/inventory/model/staff/Staff.java
  src/main/java/seedu/inventory/model/staff/Username.java
  src/test/java/seedu/inventory/logic/commands/CommandTestUtil.java
  src/test/java/seedu/inventory/model/staff/NameTest.java
  src/test/java/seedu/inventory/model/staff/PasswordTest.java
  src/test/java/seedu/inventory/model/staff/StaffTest.java
  src/test/java/seedu/inventory/model/staff/UsernameTest.java
  src/test/java/seedu/inventory/testutil/StaffBuilder.java
  src/test/java/seedu/inventory/testutil/TypicalStaffs.java
Labels: status.done, type.story, type.task

#23 Sales Order model
  docs/UserGuide.adoc
  src/main/java/seedu/inventory/model/sale/Sale.java
  src/main/java/seedu/inventory/model/sale/SaleDate.java
  src/main/java/seedu/inventory/model/sale/SaleProduct.java
  src/main/java/seedu/inventory/model/sale/SaleQuantity.java
  src/test/java/seedu/inventory/model/sale/SaleDateTest.java
  src/test/java/seedu/inventory/model/sale/SaleProductTest.java
  src/test/java/seedu/inventory/model/sale/SaleQuantityTest.java
  src/test/java/seedu/inventory/model/sale/SaleTest.java
Labels: status.done

#36 [v1.2] Staff Models Improvement
  src/main/java/seedu/inventory/model/ReadOnlyStaffList.java
  src/main/java/seedu/inventory/model/StaffList.java
  src/main/java/seedu/inventory/model/UserSession.java
  src/main/java/seedu/inventory/model/staff/UniqueStaffList.java
  src/main/java/seedu/inventory/model/staff/exceptions/DuplicateStaffException.java
  src/main/java/seedu/inventory/model/staff/exceptions/StaffNotFoundException.java
  src/test/java/seedu/inventory/model/StaffListTest.java
  src/test/java/seedu/inventory/model/UserSessionTest.java
  src/test/java/seedu/inventory/model/staff/StaffTest.java
  src/test/java/seedu/inventory/model/staff/UniqueStaffListTest.java
  src/test/java/seedu/inventory/testutil/TypicalStaffs.java
Labels: component.model, priority.high, status.done

#52 updated address book references
  README.adoc
  build.gradle
  docs/AboutUs.adoc
  docs/ContactUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: status.done

#69 More enhencement on CSVUtil
  .gitignore
  docs/DeveloperGuide.adoc
  src/main/java/seedu/inventory/commons/exceptions/UnrecognizableDataException.java
  src/main/java/seedu/inventory/commons/util/CsvUtil.java
  src/main/java/seedu/inventory/storage/CsvAdaptedData.java
  src/main/java/seedu/inventory/storage/CsvAdaptedSalesList.java
  src/test/data/CsvUtilTest/empty.csv
  src/test/data/CsvUtilTest/invalidContent.csv
  src/test/data/CsvUtilTest/invalidDataField.csv
  src/test/data/CsvUtilTest/invalidDataType.csv
  src/test/data/CsvUtilTest/missingDataField.csv
  src/test/data/CsvUtilTest/missingDataType.csv
  src/test/data/CsvUtilTest/validTest.csv
  src/test/java/seedu/inventory/commons/util/CsvUtilTest.java
Labels: priority.high, status.done

#76 Add _reposense/config.json to enable reposense
  .gitignore
  _reposense/config.json
Labels: priority.high, status.done

#77 DG updating for Milestone 1.2
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ExportCsvItemCommandSequenceDiagram.pptx
  docs/images/ExportCsvItemCommandSequenceDiagram.png
  docs/team/fzdy1914.adoc
Labels: component.docs, priority.high, status.done

#72 Storage for StaffList component
  src/main/java/seedu/inventory/MainApp.java
  src/main/java/seedu/inventory/commons/core/Messages.java
  src/main/java/seedu/inventory/commons/events/model/StaffListChangedEvent.java
  src/main/java/seedu/inventory/logic/commands/AddStaffCommand.java
  src/main/java/seedu/inventory/logic/commands/DeleteStaffCommand.java
  src/main/java/seedu/inventory/logic/commands/LoginCommand.java
  src/main/java/seedu/inventory/logic/parser/AddStaffCommandParser.java
  src/main/java/seedu/inventory/logic/parser/CliSyntax.java
  src/main/java/seedu/inventory/logic/parser/DeleteStaffCommandParser.java
  src/main/java/seedu/inventory/logic/parser/InventoryParser.java
  src/main/java/seedu/inventory/logic/parser/LoginCommandParser.java
  src/main/java/seedu/inventory/logic/parser/ParserUtil.java
  src/main/java/seedu/inventory/model/Inventory.java
  src/main/java/seedu/inventory/model/Model.java
  src/main/java/seedu/inventory/model/ModelManager.java
  src/main/java/seedu/inventory/model/ReadOnlyInventory.java
  src/main/java/seedu/inventory/model/UserPrefs.java
  src/main/java/seedu/inventory/model/VersionedInventory.java
  src/main/java/seedu/inventory/model/staff/Password.java
  src/main/java/seedu/inventory/model/staff/Staff.java
  src/main/java/seedu/inventory/model/staff/StaffName.java
  src/main/java/seedu/inventory/model/util/SampleDataUtil.java
  src/main/java/seedu/inventory/storage/StaffStorage.java
  src/main/java/seedu/inventory/storage/Storage.java
  src/main/java/seedu/inventory/storage/StorageManager.java
  src/main/java/seedu/inventory/storage/XmlAdaptedStaff.java
  src/main/java/seedu/inventory/storage/XmlFileStorage.java
  src/main/java/seedu/inventory/storage/XmlSerializableInventory.java
  src/main/java/seedu/inventory/storage/XmlSerializableStaffList.java
  src/main/java/seedu/inventory/storage/XmlStaffListStorage.java
  src/test/data/XmlSerializableStaffListTest/duplicateStaffStaffList.xml
  src/test/data/XmlSerializableStaffListTest/invalidStaffStaffList.xml
  src/test/data/XmlSerializableStaffListTest/typicalStaffsStaffList.xml
  src/test/data/XmlStaffListStorageTest/NotXmlFormatStaffList.xml
  src/test/data/XmlStaffListStorageTest/invalidAndValidStaffStaffList.xml
  src/test/data/XmlStaffListStorageTest/invalidStaffStaffList.xml
  src/test/java/seedu/inventory/TestApp.java
  src/test/java/seedu/inventory/logic/LogicManagerTest.java
  src/test/java/seedu/inventory/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/inventory/logic/commands/AddCommandTest.java
  src/test/java/seedu/inventory/logic/commands/ClearCommandTest.java
  src/test/java/seedu/inventory/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/inventory/logic/commands/EditCommandTest.java
  src/test/java/seedu/inventory/logic/commands/FindCommandTest.java
  src/test/java/seedu/inventory/logic/commands/ListCommandTest.java
  src/test/java/seedu/inventory/logic/commands/RedoCommandTest.java
  src/test/java/seedu/inventory/logic/commands/SelectCommandTest.java
  src/test/java/seedu/inventory/logic/commands/UndoCommandTest.java
  src/test/java/seedu/inventory/model/InventoryTest.java
  src/test/java/seedu/inventory/model/ModelManagerTest.java
  src/test/java/seedu/inventory/model/staff/NameTest.java
  src/test/java/seedu/inventory/model/staff/StaffNameTest.java
  src/test/java/seedu/inventory/model/staff/StaffTest.java
  src/test/java/seedu/inventory/storage/StorageManagerTest.java
  src/test/java/seedu/inventory/storage/XmlAdaptedStaffTest.java
  src/test/java/seedu/inventory/storage/XmlSerializableStaffListTest.java
  src/test/java/seedu/inventory/storage/XmlStaffListStorageTest.java
  src/test/java/seedu/inventory/testutil/StaffBuilder.java
  src/test/java/seedu/inventory/testutil/TypicalStaffs.java
Labels: priority.high, status.done, type.epic

#73 Integrated Purchase Order in Inventory manager (Model/Storage/Logic/UI)
  src/main/java/seedu/inventory/commons/events/model/AccessItemEvent.java
  src/main/java/seedu/inventory/commons/events/model/AccessPurchaseOrderEvent.java
  src/main/java/seedu/inventory/commons/events/ui/PurchaseOrderSelectionChangedEvent.java
  src/main/java/seedu/inventory/logic/Logic.java
  src/main/java/seedu/inventory/logic/LogicManager.java
  src/main/java/seedu/inventory/logic/commands/ListCommand.java
  src/main/java/seedu/inventory/logic/commands/purchaseorder/GeneratePurchaseOrderCommand.java
  src/main/java/seedu/inventory/logic/commands/purchaseorder/ListPurchaseOrderCommand.java
  src/main/java/seedu/inventory/logic/parser/CliSyntax.java
  src/main/java/seedu/inventory/logic/parser/InventoryParser.java
  src/main/java/seedu/inventory/logic/parser/ParserUtil.java
  src/main/java/seedu/inventory/logic/parser/purchaseorder/GeneratePurchaseOrderCommandParser.java
  src/main/java/seedu/inventory/model/Inventory.java
  src/main/java/seedu/inventory/model/Model.java
  src/main/java/seedu/inventory/model/ModelManager.java
  src/main/java/seedu/inventory/model/ReadOnlyInventory.java
  src/main/java/seedu/inventory/model/item/Quantity.java
  src/main/java/seedu/inventory/model/purchaseorder/NonUniquePurchaseOrderList.java
  src/main/java/seedu/inventory/model/purchaseorder/PurchaseOrder.java
  src/main/java/seedu/inventory/model/purchaseorder/Quantity.java
  src/main/java/seedu/inventory/model/purchaseorder/exceptions/PurchaseOrderNotFoundException.java
  src/main/java/seedu/inventory/storage/XmlAdaptedPurchaseOrder.java
  src/main/java/seedu/inventory/storage/XmlSerializableInventory.java
  src/main/java/seedu/inventory/ui/BrowserPanel.java
  src/main/java/seedu/inventory/ui/MainWindow.java
  src/main/java/seedu/inventory/ui/purchaseorder/PurchaseOrderCard.java
  src/main/java/seedu/inventory/ui/purchaseorder/PurchaseOrderListPanel.java
  src/main/resources/view/PurchaseOrderListCard.fxml
  src/main/resources/view/PurchaseOrderListPanel.fxml
  src/test/data/XmlSerializableInventoryTest/invalidPurchaseOrderInventory.xml
  src/test/data/XmlSerializableInventoryTest/typicalPurchaseOrderInventory.xml
  src/test/java/seedu/inventory/logic/LogicManagerTest.java
  src/test/java/seedu/inventory/logic/commands/AddCommandTest.java
  src/test/java/seedu/inventory/logic/commands/CommandTestUtil.java
  src/test/java/seedu/inventory/logic/commands/CreateSaleCommandTest.java
  src/test/java/seedu/inventory/logic/commands/purchaseorder/GeneratePurchaseOrderCommandTest.java
  src/test/java/seedu/inventory/logic/commands/purchaseorder/ListPurchaseOrderCommandTest.java
  src/test/java/seedu/inventory/logic/parser/InventoryParserTest.java
  src/test/java/seedu/inventory/logic/parser/purchaseorder/GeneratePurchaseOrderParserTest.java
  src/test/java/seedu/inventory/model/InventoryTest.java
  src/test/java/seedu/inventory/model/ModelManagerTest.java
  src/test/java/seedu/inventory/model/purchaseorder/NonUniquePurchaseOrderListTest.java
  src/test/java/seedu/inventory/model/purchaseorder/PurchaseOrderTest.java
  src/test/java/seedu/inventory/model/purchaseorder/QuantityTest.java
  src/test/java/seedu/inventory/storage/XmlAdaptedPurchaseOrderTest.java
  src/test/java/seedu/inventory/storage/XmlSerializableInventoryTest.java
  src/test/java/seedu/inventory/testutil/InventoryBuilder.java
  src/test/java/seedu/inventory/testutil/ModelStub.java
  src/test/java/seedu/inventory/testutil/purchaseorder/PurchaseOrderBuilder.java
  src/test/java/seedu/inventory/testutil/purchaseorder/PurchaseOrderUtil.java
  src/test/java/seedu/inventory/testutil/purchaseorder/TypicalPurchaseOrder.java
Labels: component.logic, component.model, component.storage, component.ui, status.ongoing, type.epic

#83 DG changes for point 1 and 5
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/esmondtan.adoc
Labels: component.docs, status.done

#82 Update on UGDG Draft 1
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/darren96.adoc
Labels: component.docs, status.done

#91 list-sale, delete-sale command and UI changes + lots of test cases
  docs/UserGuide.adoc
  src/main/java/seedu/inventory/commons/events/model/AccessSaleEvent.java
  src/main/java/seedu/inventory/commons/events/ui/SalePanelSelectionChangedEvent.java
  src/main/java/seedu/inventory/logic/Logic.java
  src/main/java/seedu/inventory/logic/LogicManager.java
  src/main/java/seedu/inventory/logic/commands/sale/AddSaleCommand.java
  src/main/java/seedu/inventory/logic/commands/sale/DeleteSaleCommand.java
  src/main/java/seedu/inventory/logic/commands/sale/ListSaleCommand.java
  src/main/java/seedu/inventory/logic/parser/InventoryParser.java
  src/main/java/seedu/inventory/logic/parser/ParserUtil.java
  src/main/java/seedu/inventory/logic/parser/sale/AddSaleCommandParser.java
  src/main/java/seedu/inventory/logic/parser/sale/DeleteSaleCommandParser.java
  src/main/java/seedu/inventory/model/Model.java
  src/main/java/seedu/inventory/model/ModelManager.java
  src/main/java/seedu/inventory/ui/MainWindow.java
  src/main/java/seedu/inventory/ui/sale/SaleCard.java
  src/main/java/seedu/inventory/ui/sale/SaleListPanel.java
  src/main/resources/view/SaleListCard.fxml
  src/main/resources/view/SaleListPanel.fxml
  src/test/java/guitests/guihandles/SaleCardHandle.java
  src/test/java/seedu/inventory/logic/commands/sale/AddSaleCommandTest.java
  src/test/java/seedu/inventory/logic/commands/sale/DeleteSaleCommandTest.java
  src/test/java/seedu/inventory/logic/commands/sale/ListSaleCommandTest.java
  src/test/java/seedu/inventory/logic/parser/ParserUtilTest.java
  src/test/java/seedu/inventory/logic/parser/sale/AddSaleCommandParserTest.java
  src/test/java/seedu/inventory/logic/parser/sale/DeleteSaleCommandParserTest.java
  src/test/java/seedu/inventory/model/sale/UniqueSaleListTest.java
  src/test/java/seedu/inventory/testutil/ModelStub.java
  src/test/java/seedu/inventory/ui/SaleCardTest.java
  src/test/java/seedu/inventory/ui/testutil/GuiTestAssert.java
Labels: status.done

#90 Update component in charge in AboutUs and remove navigation bar in ne…
  build.gradle
  docs/AboutUs.adoc
  docs/images/InventoryManagerLogo.png
  docs/templates/_header.html.slim
Labels: component.docs

#93 Documentation Updates + Doc Structure Changes
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/Ui.png
  docs/images/doc-add-sale-failed.png
  docs/images/doc-command-box.png
  docs/images/doc-delete-sale-failed.png
  docs/images/doc-list-sale.png
  docs/images/doc-ui.png
Labels: status.done

#97 List Staff Command
  src/main/java/seedu/inventory/logic/commands/staff/ListStaffCommand.java
  src/main/java/seedu/inventory/logic/parser/InventoryParser.java
  src/test/java/seedu/inventory/logic/commands/staff/ListStaffCommandTest.java
Labels: component.logic, priority.high, status.done, type.epic

#99 Add some ui test cases for staff component
  src/test/java/guitests/guihandles/StaffCardHandle.java
  src/test/java/guitests/guihandles/StaffListPanelHandle.java
  src/test/java/seedu/inventory/ui/StaffCardTest.java
  src/test/java/seedu/inventory/ui/StaffListPanelTest.java
  src/test/java/seedu/inventory/ui/testutil/GuiTestAssert.java
Labels: component.ui, status.done

#101 Change in docs
  README.adoc
  build.gradle
  docs/images/Ui.png
  docs/team/darren96.adoc
Labels: component.docs, status.done

#102 Changed addressbook.jar to inventorymanager.jar
  build.gradle
Labels: component.storage, severity.low, status.done

#109 Added command for searching items by SKU
  src/main/java/seedu/inventory/commons/util/StringUtil.java
  src/main/java/seedu/inventory/logic/commands/FindItemSkuCommand.java
  src/main/java/seedu/inventory/logic/parser/FindItemSkuCommandParser.java
  src/main/java/seedu/inventory/logic/parser/InventoryParser.java
  src/main/java/seedu/inventory/model/item/Sku.java
  src/main/java/seedu/inventory/model/item/SkuContainsKeywordsPredicate.java
  src/test/java/seedu/inventory/logic/parser/FindItemCommandParserTest.java
  src/test/java/seedu/inventory/logic/parser/FindItemSkuCommandParserTest.java
  src/test/java/seedu/inventory/logic/parser/InventoryParserTest.java
  src/test/java/seedu/inventory/model/item/SkuContainsKeywordsPredicateTest.java
  src/test/java/seedu/inventory/model/item/SkuMatchPredicateTest.java
  src/test/java/systemtests/FindItemSkuCommandSystemTest.java
Labels: component.logic, component.model, priority.high, status.done, type.enhancement

#105 Signout the Users from the system
  src/main/java/seedu/inventory/logic/commands/LoginCommand.java
  src/main/java/seedu/inventory/logic/commands/LogoutCommand.java
  src/main/java/seedu/inventory/logic/parser/InventoryParser.java
  src/main/java/seedu/inventory/model/Inventory.java
  src/main/java/seedu/inventory/model/Model.java
  src/main/java/seedu/inventory/model/ModelManager.java
  src/main/java/seedu/inventory/model/UserSession.java
  src/main/java/seedu/inventory/model/VersionedInventory.java
  src/main/java/seedu/inventory/model/staff/Staff.java
  src/test/java/seedu/inventory/logic/commands/LoginCommandTest.java
  src/test/java/seedu/inventory/logic/commands/LogoutCommandTest.java
  src/test/java/seedu/inventory/logic/parser/LoginCommandParserTest.java
  src/test/java/seedu/inventory/model/ModelManagerTest.java
  src/test/java/seedu/inventory/testutil/ModelStub.java
Labels: priority.high, status.done

#108 Added Review(Approve/Reject) feature for Purchase Order
  src/main/java/seedu/inventory/logic/commands/purchaseorder/ApprovePurchaseOrderCommand.java
  src/main/java/seedu/inventory/logic/commands/purchaseorder/RejectPurchaseOrderCommand.java
  src/main/java/seedu/inventory/logic/parser/InventoryParser.java
  src/main/java/seedu/inventory/logic/parser/purchaseorder/ApprovePurchaseOrderCommandParser.java
  src/main/java/seedu/inventory/logic/parser/purchaseorder/RejectPurchaseOrderCommandParser.java
  src/main/java/seedu/inventory/model/purchaseorder/PurchaseOrder.java
  src/test/java/seedu/inventory/logic/commands/CommandTestUtil.java
  src/test/java/seedu/inventory/logic/commands/SelectCommandTest.java
  src/test/java/seedu/inventory/logic/commands/purchaseorder/AddPurchaseOrderCommandTest.java
  src/test/java/seedu/inventory/logic/commands/purchaseorder/ApprovePurchaseOrderCommandTest.java
  src/test/java/seedu/inventory/logic/commands/purchaseorder/DeletePurchaseOrderCommandTest.java
  src/test/java/seedu/inventory/logic/commands/purchaseorder/RejectPurchaseOrderCommandTest.java
  src/test/java/seedu/inventory/logic/parser/InventoryParserTest.java
  src/test/java/seedu/inventory/logic/parser/purchaseorder/ApprovePurchaseOrderParserTest.java
  src/test/java/seedu/inventory/logic/parser/purchaseorder/DeletePurchaseOrderParserTest.java
  src/test/java/seedu/inventory/logic/parser/purchaseorder/RejectPurchaseOrderParserTest.java
  src/test/java/seedu/inventory/storage/XmlAdaptedPurchaseOrderTest.java
  src/test/java/seedu/inventory/testutil/TypicalItems.java
Labels: component.logic, priority.high, status.done

#111 Add change password command
  src/main/java/seedu/inventory/logic/commands/authentication/ChangePasswordCommand.java
  src/main/java/seedu/inventory/logic/commands/authentication/LoginCommand.java
  src/main/java/seedu/inventory/logic/commands/authentication/LogoutCommand.java
  src/main/java/seedu/inventory/logic/parser/InventoryParser.java
  src/main/java/seedu/inventory/logic/parser/ParserUtil.java
  src/main/java/seedu/inventory/logic/parser/authentication/ChangePasswordCommandParser.java
  src/main/java/seedu/inventory/logic/parser/authentication/LoginCommandParser.java
  src/main/java/seedu/inventory/model/Inventory.java
  src/main/java/seedu/inventory/model/staff/Password.java
  src/test/java/seedu/inventory/logic/commands/authentication/ChangePasswordCommandTest.java
  src/test/java/seedu/inventory/logic/commands/authentication/LoginCommandTest.java
  src/test/java/seedu/inventory/logic/commands/authentication/LogoutCommandTest.java
  src/test/java/seedu/inventory/logic/parser/authentication/ChangePasswordCommandParserTest.java
  src/test/java/seedu/inventory/logic/parser/authentication/LoginCommandParserTest.java
  src/test/java/seedu/inventory/logic/parser/staff/AddStaffCommandParserTest.java
  src/test/java/seedu/inventory/logic/parser/staff/EditStaffCommandParserTest.java
Labels: priority.high, status.done

#110 Added Edit purchase order command
  src/main/java/seedu/inventory/logic/commands/purchaseorder/EditPurchaseOrderCommand.java
  src/main/java/seedu/inventory/logic/parser/InventoryParser.java
  src/main/java/seedu/inventory/logic/parser/purchaseorder/EditPurchaseOrderCommandParser.java
  src/test/java/seedu/inventory/logic/commands/CommandTestUtil.java
  src/test/java/seedu/inventory/logic/commands/purchaseorder/EditPurchaseOrderCommandTest.java
  src/test/java/seedu/inventory/logic/parser/purchaseorder/EditPurchaseOrderCommandParserTest.java
  src/test/java/seedu/inventory/testutil/purchaseorder/EditPurchaseOrderDescriptorBuilder.java
  src/test/java/seedu/inventory/testutil/purchaseorder/PurchaseOrderUtil.java
  src/test/java/seedu/inventory/testutil/purchaseorder/TypicalPurchaseOrder.java
Labels: component.logic, status.done

#112 Enabling the apps to do authentication and authorization
  src/main/java/seedu/inventory/logic/Logic.java
  src/main/java/seedu/inventory/logic/LogicManager.java
  src/main/java/seedu/inventory/model/util/SampleDataUtil.java
  src/test/java/seedu/inventory/TestApp.java
  src/test/java/seedu/inventory/logic/LogicManagerTest.java
  src/test/java/seedu/inventory/logic/parser/InventoryParserTest.java
  src/test/java/seedu/inventory/ui/CommandBoxTest.java
Labels: component.logic, status.done, type.enhancement

#117 User Guide Changes + Portfolio Changes
  README.adoc
  docs/UserGuide.adoc
  docs/images/Ui.png
  docs/images/doc-change-password.png
  docs/images/doc-delete-po.png
  docs/images/doc-delete-user-failed.png
  docs/images/doc-export-csv-item.png
  docs/images/doc-find-item.png
  docs/images/doc-list-item.png
  docs/images/doc-list-po.png
  docs/images/doc-list-user.png
  docs/images/doc-login.png
  docs/images/image-delete-staff.png
  docs/team/esmondtan.adoc
Labels: status.done

#118 Edit UG and DG on user management and authentication
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/doc-change-password.png
  docs/team/darren96.adoc
Labels: component.docs, status.done

#119 Updated portfolio and User Guide
  docs/UserGuide.adoc
  docs/team/yao-tx.adoc
Labels: component.docs, status.done

#120 Broken image in readme fixed
  README.adoc
Labels: status.done

#121 Fix required date bug
  src/main/java/seedu/inventory/logic/parser/ParserUtil.java
  src/main/java/seedu/inventory/model/purchaseorder/RequiredDate.java
  src/main/java/seedu/inventory/storage/XmlAdaptedPurchaseOrder.java
  src/test/java/seedu/inventory/model/purchaseorder/RequiredDateTest.java
Labels: severity.low, status.done

#124 Disable select command for staff, sales and purchase order
  src/main/java/seedu/inventory/logic/commands/SelectCommand.java
  src/main/java/seedu/inventory/ui/BrowserPanel.java
Labels: component.logic, severity.low, status.done

#126 Updated user guide
  docs/UserGuide.adoc
Labels: component.docs, status.done

#128 Fixed edit item and purchase order bug + more test cases
  src/main/java/seedu/inventory/logic/commands/item/EditItemCommand.java
  src/main/java/seedu/inventory/logic/commands/purchaseorder/EditPurchaseOrderCommand.java
  src/main/java/seedu/inventory/model/Inventory.java
  src/main/java/seedu/inventory/model/Model.java
  src/main/java/seedu/inventory/model/ModelManager.java
  src/main/java/seedu/inventory/ui/purchaseorder/PurchaseOrderCard.java
  src/test/java/guitests/guihandles/PurchaseOrderCardHandle.java
  src/test/java/guitests/guihandles/PurchaseOrderListPanelHandle.java
  src/test/java/seedu/inventory/logic/parser/purchaseorder/EditPurchaseOrderCommandParserTest.java
  src/test/java/seedu/inventory/model/InventoryTest.java
  src/test/java/seedu/inventory/model/ModelManagerTest.java
  src/test/java/seedu/inventory/testutil/ModelStub.java
  src/test/java/seedu/inventory/ui/PurchaseOrderCardTest.java
  src/test/java/seedu/inventory/ui/PurchaseOrderListPanelTest.java
  src/test/java/seedu/inventory/ui/testutil/GuiTestAssert.java
Labels: status.done, type.bug

#130 Change where Password.hash method is used + Clear Command Debug
  src/main/java/seedu/inventory/logic/commands/ClearCommand.java
  src/main/java/seedu/inventory/model/Inventory.java
  src/main/java/seedu/inventory/model/UserPrefs.java
  src/main/java/seedu/inventory/model/util/SampleDataUtil.java
  src/main/java/seedu/inventory/storage/XmlSerializableInventory.java
  src/test/data/CsvSerializableStaffListTest/typicalStaffList.csv
  src/test/data/XmlSerializableStaffListTest/typicalStaffsStaffList.xml
  src/test/java/seedu/inventory/TestApp.java
  src/test/java/seedu/inventory/logic/commands/ClearCommandTest.java
  src/test/java/seedu/inventory/logic/commands/authentication/ChangePasswordCommandTest.java
  src/test/java/seedu/inventory/logic/parser/InventoryParserTest.java
  src/test/java/seedu/inventory/logic/parser/authentication/LoginCommandParserTest.java
  src/test/java/seedu/inventory/logic/parser/staff/AddStaffCommandParserTest.java
  src/test/java/seedu/inventory/logic/parser/staff/EditStaffCommandParserTest.java
  src/test/java/seedu/inventory/model/staff/StaffTest.java
  src/test/java/seedu/inventory/testutil/staff/EditStaffDescriptorBuilder.java
  src/test/java/seedu/inventory/testutil/staff/StaffBuilder.java
  src/test/java/seedu/inventory/testutil/staff/TypicalStaffs.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/InventorySystemTest.java
  src/test/java/systemtests/ModelHelper.java
Labels: status.done, type.enhancement

#132 update version number for our testing release
  src/main/java/seedu/inventory/MainApp.java
Labels: status.done

#131 Fix bugs
  docs/UserGuide.adoc
  src/main/java/seedu/inventory/MainApp.java
  src/main/java/seedu/inventory/commons/core/Messages.java
Labels: severity.low, status.ongoing, type.bug

#141 Fix Clear/Undo/Redo command bugs
  src/main/java/seedu/inventory/logic/Logic.java
  src/main/java/seedu/inventory/logic/LogicManager.java
  src/main/java/seedu/inventory/model/ModelManager.java
  src/main/java/seedu/inventory/model/VersionedInventory.java
  src/test/java/seedu/inventory/TestApp.java
  src/test/java/seedu/inventory/logic/LogicManagerTest.java
Labels: priority.medium, status.done

#144 Bug fix for 1.3 releases
  src/main/java/seedu/inventory/logic/LogicManager.java
  src/main/java/seedu/inventory/logic/commands/staff/DeleteStaffCommand.java
Labels: status.done

#146 Bug Fixes
  src/main/java/seedu/inventory/logic/commands/ClearCommand.java
  src/main/java/seedu/inventory/logic/commands/sale/DeleteSaleCommand.java
  src/main/java/seedu/inventory/model/Model.java
Labels: status.done

#148 Bug fix for user-session not updated after password changed
  src/main/java/seedu/inventory/logic/commands/authentication/ChangePasswordCommand.java
  src/main/java/seedu/inventory/model/Model.java
  src/main/java/seedu/inventory/model/ModelManager.java
  src/test/java/seedu/inventory/logic/commands/authentication/ChangePasswordCommandTest.java
  src/test/java/seedu/inventory/testutil/ModelStub.java
Labels: status.done

#143 Small Fix of Output Message
  src/main/java/seedu/inventory/commons/events/model/SaleListChangedEvent.java
  src/main/java/seedu/inventory/commons/events/storage/PurchaseOrderListUpdateEvent.java
  src/main/java/seedu/inventory/storage/StorageManager.java
Labels: status.done
